version: '2.3'
services:
  nginx:
    depends_on:
      - task-environment
    image: nginx:1.18
    volumes:
      - "./nginx_config/my_site:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    restart: unless-stopped
  task-environment:
    image: registry.insight-centre.org/annsou/task-environment:session
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    volumes:
      - "./static/videos:/app/static/videos"
      - "./static/audio:/app/static/audio"
      - "./static/data:/app/static/data"
      - "./saved-times.db:/app/saved-times.db"
    environment:
      - SESSION_NUMBER=${SESSION_NUMBER}
      - MATH_TASK_LEVEL=${MATH_TASK_LEVEL}
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    restart: unless-stopped
